version: '2'
services:
  web:
    restart: always
    build: ./web
    ports:
      - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000
  
  db:
    restart: always
    image: postgres:9
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=djangodb